version: "3.9"
services:

  main:
    container_name: ubuntu-dev
    build:
      context: src
    environment:
      currency: BTC
      prefix: 1Test 1test
    volumes:
      - ./temp/volume/results:/results
