version: "3.9"
services:

  main:
    container_name: vanitygenPlusplus-dev
    network_mode: none
    build:
      context: src
    environment:
      currency: BTC
      prefix: 1Test 1test 1Jaid 1jaid
      amount: 10
      threads: 1
    volumes:
      - ./temp/volume/results:/results
